site_name: Documentação Central | Alexandre
site_description: Guias, referências e arquitetura do projeto
site_author: "Equipe de Engenharia de Software da UnB"

theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate

nav:
  - Início: index.md