name: História de Usuário
description: Utilize este template para mapear e especificar novos requisitos funcionais do sistema.
title: '[USXX] - '
labels: [enhancement, documentation]
body:
  - type: markdown
    attributes:
      value: |
        ### Detalhamento de Requisito
        Preencha os campos abaixo estruturar a nova funcionalidade.
        
  - type: input
    id: epic
    attributes:
      label: Épico (Módulo) e Ator
      description: Qual é o Épico desta US e quem é o usuário final?
      placeholder: Ex. EP06 - CRM / Ator Cliente
    validations:
      required: true
      
  - type: textarea
    id: story
    attributes:
      label: História de Usuário
      value: |
        **Como** [ator],
        **Quero** [ação ou funcionalidade],
        **Para que** [valor ou objetivo gerado].
    validations:
      required: true
      
  - type: textarea
    id: criteria
    attributes:
      label: Critérios de Aceite
      description: Liste as condições exatas que precisam ser atendidas.
      value: |
        - [ ] Critério 1
        - [ ] Critério 2
    validations:
      required: true
      
  - type: textarea
    id: references
    attributes:
      label: Anexos e Referências
      description: Links para a documentação, PRs ou discussões anteriores.
    validations:
      required: false